<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: admin
 * Date: Fri, 10 Mar 2017 09:44:12 +0000
 */

$conf['title'] = 'Test Wiki';
$conf['template'] = 'selfthinker-dokuwiki_template_writr-ce85a6d';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
