<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Sun, 09 Apr 2017 04:19:43 +0000
 */

$conf['title'] = 'Dokuwiki INT322';
$conf['template'] = 'notconscious-dokuwiki-template-adoradark-e903fa0';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['subscribers'] = 1;
$conf['plugin']['captcha']['mode'] = 'math';
$conf['plugin']['captcha']['loginprotect'] = 1;

// end auto-generated content
